---
# tasks file for remoteiot-client

- name: Install JVM - RedHat-based
  package:
    name: java-1.8.0-openjdk*
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  register: result

- name: Install JVM - Others
  package:
    name: openjdk-8-jre-headless
    state: present
  when: result is skipped

- name: Check if Service Exists
  stat: path=/etc/init.d/remote-iot
  register: service_status

- name: Setup
  shell: "curl -s -L 'https://remoteiot.com/install/install.sh' | sudo bash -s '{{ setup_key }}' '{{ setup_name }}' '{{ setup_note }}' '{{ setup_group }}'"
  notify: Restart RemoteIoT
  when: not service_status.stat.exists

- name: Reduce mobile data usage
  lineinfile:
    path: /etc/remoteiot.conf
    state: present
    regexp: "^AliveInterval="
    line: "AliveInterval={{ alive_interval }}"
  notify: Restart RemoteIoT
  when: reduce_usage
